### ISSUE TITLE
How to visualize the output.pkl after video inference?

### ISSUE THREAD

**Issue by Frank-Dz** [vegesm/pose_refinement#5]
How to visualize the output.pkl after video inference?

**Comment by vegesm** [comment]
I've added the util/viz.py file that lets you draw 3D plots of skeletons via the show3Dpose functions. It is per-frame only though, does not handle videos.

**Comment by Frank-Dz** [comment]
> I've added the util/viz.py file that lets you draw 3D plots of skeletons via the show3Dpose functions. It is per-frame only though, does not handle videos.

It helps me a lot thanks!
